version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.3.2
jobs:
  build_project:
    working_directory: ~/gui-deploy
    docker:
      - image: node:10.15.3
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: cd test-fe && npm i
      - run:
          name: Building project
          command: cd test-fe && npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy_project:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Upload file to S3
          command: aws s3 sync ./gui/build/ s3://test-circleci-fe --delete
workflows:
  version: 2
  build:
    jobs:
      - build_project
      - deploy_project:
          requires:
            - build_project
          context: aws-context
